### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by programen-gh** [programen-gh/protospace-33071#1]
# URL
https://protospace-33071.herokuapp.com/

**Comment by tech-taro** [comment]
programen-ghさん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
【プロトタイプ投稿機能】
・投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること
→ページに留まらず下記画面に飛んでしまいますので、修正をお願いします。（404エラーが何かも調べてみてください）
<img width="687" alt="スクリーンショット 2020-12-23 11 22 30" src="https://user-images.githubusercontent.com/69299868/102951985-6cf9c180-4511-11eb-82b6-5ba20c4dd2e1.png">

・必要な情報を入力すると、投稿ができること
→正しい情報を入力し投稿ボタンを押したところ、上記画面が表示されました。合わせて修正をお願いします。



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by programen-gh** [comment]
tech-taroさん、ご確認ありがとうございます。
上記、修正依頼箇所につきまして修正完了しました。
